// https://dbdiagram.io/d/strimq-67aef4cf263d6cf9a025fe16
enum tier {
  free_trial [note: 'Free Trial tier will get their infras data wiped after 30 days']
  bronze
  silver
  gold
  platinum [note: 'Platinum tier will get their own dedicated infra']
}


Table Tenants {
  id UUID [pk]
  name varchar(255)
  domain varchar(255)
  tier tier
  infras_id UUID [ref: > TenantInfras.id]

  created_at timestamp
  updated_at timestamp
}

Table TenantInfras {
  id UUID [pk]
  name varchar(255)
  kafka_brokers "varchar(255)[]"
  schema_registry_url varchar(255)
  kafka_connect_url varchar(255)
  kms_key varchar(255)

  created_at timestamp
  updated_at timestamp
}

Table Sources {
  id UUID [pk]
  tenant_id UUID [ref: > Tenants.id]
  name varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SourceTags {
  id UUID [pk]
  source_id UUID [ref: > Sources.id]
  key varchar(255)
  value varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SourceAppConfigs {
  id UUID [pk]
  source_id UUID [ref: > Sources.id]
  key varchar(255)
  value varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SourceAppTables {
  id UUID [pk]
  source_id UUID [ref: > Sources.id]
  table_name varchar(255)
  schema varchar(255)
  database varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SourceKCConnectors {
  id UUID [pk]
  source_id UUID [ref: > Sources.id]
  name varchar(255) [not null, unique]
  connector_class varchar(255)
  version varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SourceKCConfigs {
  id UUID [pk]
  source_kc_connector_id UUID [ref: > SourceKCConnectors.id]
  key varchar(255)
  value text
  
  created_at timestamp
  updated_at timestamp
}

Table Sinks {
  id UUID [pk]
  tenant_id UUID [ref: > Tenants.id]
  name varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SinkTags {
  id UUID [pk]
  sink_id UUID [ref: > Sinks.id]
  key varchar(255)
  value varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SinkAppConfigs {
  id UUID [pk]
  sink_id UUID [ref: > Sinks.id]
  key varchar(255)
  value varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table SinkKCConnectors {
  id UUID [pk]
  sink_id UUID [ref: > Sinks.id]
  name varchar(255) [not null, unique]
  connector_class varchar(255)
  version varchar(255)

  created_at timestamp
  updated_at timestamp
}

Table SinkKCConfigs {
  id UUID [pk]
  sink_kc_connector_id UUID [ref: > SinkKCConnectors.id]
  key varchar(255)
  value text
  
  created_at timestamp
  updated_at timestamp
}

Table Pipelines {
  id UUID [pk]
  tenant_id UUID [ref: > Tenants.id]
  source_id UUID [ref: > Sources.id]
  sink_id UUID [ref: > Sinks.id]
  name varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table PipelineTags {
  id UUID [pk]
  pipeline_id int [ref: > Pipelines.id]
  key varchar(255)
  value varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table PipelineAppConfigs {
  id UUID [pk]
  pipeline_id UUID [ref: > Pipelines.id]
  key varchar(255)
  value varchar(255)
  
  created_at timestamp
  updated_at timestamp
}

Table PipelineTables {
  id UUID [pk]
  pipeline_id UUID [ref: > Pipelines.id]
  table_id UUID [ref: > SourceAppTables.id]
  
  created_at timestamp
  updated_at timestamp
}